version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api_auth:
    build: ./microsservices/user/
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      ENV: dev
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: db
      DB_PORT: 5432
    command: >
      /bin/sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
      "
    restart: always

  api_photo:
    build: ./microsservices/photo/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENV: dev
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_HOST: db
      DB_PORT: 5432
    command: >
      /bin/sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_auth
      - api_photo

volumes:
  postgres_data:
