version: "3.8"

services:
  auth:
    build: ./auth/
    ports:
      - "8000:8000"
    container_name: backend
    volumes:
      - ./logs:/app/logs

  filebeat:
    build: ./filebeat/
    container_name: filebeat
    volumes:
      - ./logs:/src/logs
    depends_on:
      - elasticsearch
      - kibana
    network_mode: "host"

  elasticsearch:
    build: ./elasticsearch/
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nginx:
    build: ./nginx/
    ports:
      - "3000:80"
    depends_on:
      - compra
      - auth
    volumes:
      - ./logs/nginx:/var/log/nginx

  compra:
    build: ./compra/
    ports:
      - "8001:8001"


volumes:
    elasticsearch_data:
        driver: local