version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: gyu
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./src
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
