# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres
    restart: on-failure
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: usuario
      POSTGRES_DB: ponderada_extra
      DB_PORT: 5432
    depends_on:
      - adminer

  adminer:
    image: adminer
    restart: on-failure
    container_name: adminer
    ports:
      - 8080:8080

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      /bin/sh -c "
        alembic upgrade head &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: always

  redis:
    image: redis
    restart: on-failure
    container_name: redis
    ports:
      - "6379:6379"
    
    depends_on:
      - db
      - adminer